// Code generated by hawk. DO NOT EDIT.
// Rerunning hawk will overwrite this file.
// Version: {{.Version}}
// Version Date: {{.VersionDate}}

package server

import (
	"context"
	"flag"
	"fmt"
	"github.com/sirupsen/logrus"
	"github.com/soheilhy/cmux"
	"google.golang.org/grpc/reflection"
	"net"
	"net/http"
	"net/http/pprof"
	"os"

	// 3d Party
	"google.golang.org/grpc"

	// This Service
	pb "{{.PBImportPath -}}"
	"{{.ImportPath -}} /handlers"
	"{{.ImportPath -}} /svc"
)

var DefaultConfig svc.Config

func init() {
	flag.StringVar(&DefaultConfig.DebugAddr, "debug.addr", ":5060", "Debug and metrics listen address")
	flag.StringVar(&DefaultConfig.ServiceAddr, "service.addr", ":5050", "HTTP and gRPC listen address")

	// Use environment variables, if set. Flags have priority over Env vars.
	if addr := os.Getenv("DEBUG_ADDR"); addr != "" {
		DefaultConfig.DebugAddr = addr
	}
	if port := os.Getenv("PORT"); port != "" {
		DefaultConfig.ServiceAddr = fmt.Sprintf(":%s", port)
	}
	if addr := os.Getenv("SERVICE_ADDR"); addr != "" {
		DefaultConfig.ServiceAddr = addr
	}
}

func NewEndpoints(service pb.{{.Service.Name}}Server) svc.Endpoints {
	// Business domain.

	// Wrap Service with middlewares. See handlers/middlewares.go
	service = handlers.WrapService(service)

	// Endpoint domain.
	var (
	{{range $i := .Service.Methods -}}
		{{ if and (not $i.RequestStream) (not $i.ResponseStream) }}
			{{ToLower $i.Name}}Endpoint = svc.Make{{$i.Name}}Endpoint(service)
		{{ end }}
	{{end}}
	)

	endpoints := svc.NewEndpoints()
	{{range $i := .Service.Methods -}}
		{{ if and (not $i.RequestStream) (not $i.ResponseStream) }}
			endpoints.{{$i.Name}}Endpoint = {{ToLower $i.Name}}Endpoint
		{{ end }}
	{{end}}

	// Wrap selected Endpoints with middlewares. See handlers/middlewares.go
	endpoints = handlers.WrapEndpoints(service, endpoints)

	return endpoints
}

// Run starts a new http server, gRPC server, and a debug server with the
// passed config and logger
func Run(cfg svc.Config) {
	service := handlers.NewService()
	endpoints := NewEndpoints(service)

	if cfg.GenericHTTPResponseEncoder == nil {
		cfg.GenericHTTPResponseEncoder = svc.EncodeHTTPGenericResponse
	}

	// WebSocket config
	wsCfg := svc.WebSocketConfig{
		Guard: func(ctx context.Context, r *http.Request) (context.Context, error) {
			return handlers.WebSocketGuard(ctx, service, r)
		},
		OriginChecker: func(r *http.Request) bool {
			return handlers.WebSocketOriginChecker(service, r)
		},
	}

	// Mechanical domain.
	errc := make(chan error)

	// Interrupt handler.
	go handlers.InterruptHandler(errc)

	// Debug listener.
	go func() {
		handlers.Logger.WithFields(logrus.Fields{
			"layer": "debug",
			"addr":	 cfg.DebugAddr,
		}).Info("listening")

		m := http.NewServeMux()
		m.Handle("/debug/pprof/", http.HandlerFunc(pprof.Index))
		m.Handle("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
		m.Handle("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
		m.Handle("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
		m.Handle("/debug/pprof/trace", http.HandlerFunc(pprof.Trace))

		errc <- http.ListenAndServe(cfg.DebugAddr, m)
	}()

	// HTTP, gRPC and WebSocket listener.
	l, err := net.Listen("tcp", cfg.ServiceAddr)
	if err != nil {
		handlers.Logger.WithError(err).Error("service listener error")
		return
	}
	defer l.Close()

	tcpMux := cmux.New(l)
	grpcListener := tcpMux.MatchWithWriters(cmux.HTTP2MatchHeaderFieldSendSettings("content-type", "application/grpc"))
	grpcListener2 := tcpMux.Match(cmux.HTTP2HeaderField("content-type", "application/grpc"))
	httpListener := tcpMux.Match(cmux.Any())

	// gRPC transport.
	s := grpc.NewServer()
	srv := svc.MakeGRPCServer(endpoints)
	pb.Register{{.Service.Name}}Server(s, srv)
	reflection.Register(s)

	go func() {
		errc <- s.Serve(grpcListener)
	}()
	go func() {
		errc <- s.Serve(grpcListener2)
	}()

	// HTTP transport.
	h := svc.MakeHTTPHandler(handlers.Logger, endpoints, cfg.GenericHTTPResponseEncoder, wsCfg)
	go func() {
		errc <- http.Serve(httpListener, h)
	}()

	// Start the mux.
	go func() {
		errc <- tcpMux.Serve()
	}()

	handlers.Logger.WithFields(logrus.Fields{
		"layer": "service",
		"addr":  cfg.ServiceAddr,
	}).Info("listening")

	// Run!
	handlers.Logger.WithError(<-errc).Info("exit")
}
