// Code generated by hawk. DO NOT EDIT.
// Rerunning hawk will overwrite this file.
// Version: {{.Version}}
// Version Date: {{.VersionDate}}

package server

import (
	"context"
    "flag"
    "os"
    "fmt"
	"github.com/sirupsen/logrus"
	"net"
	"net/http"
	"net/http/pprof"

	// 3d Party
	"google.golang.org/grpc"

	// This Service
	pb "{{.PBImportPath -}}"
	"{{.ImportPath -}} /svc"
	"{{.ImportPath -}} /handlers"
)

var DefaultConfig svc.Config

func init() {
	flag.StringVar(&DefaultConfig.DebugAddr, "debug.addr", ":5060", "Debug and metrics listen address")
	flag.StringVar(&DefaultConfig.HTTPAddr, "http.addr", ":5050", "HTTP listen address")
	flag.StringVar(&DefaultConfig.GRPCAddr, "grpc.addr", ":5040", "gRPC (HTTP) listen address")

	// Use environment variables, if set. Flags have priority over Env vars.
	if addr := os.Getenv("DEBUG_ADDR"); addr != "" {
		DefaultConfig.DebugAddr = addr
	}
	if port := os.Getenv("PORT"); port != "" {
		DefaultConfig.HTTPAddr = fmt.Sprintf(":%s", port)
	}
	if addr := os.Getenv("HTTP_ADDR"); addr != "" {
		DefaultConfig.HTTPAddr = addr
	}
	if addr := os.Getenv("GRPC_ADDR"); addr != "" {
		DefaultConfig.GRPCAddr = addr
	}
}

func NewEndpoints(service pb.{{.Service.Name}}Server) svc.Endpoints {
	// Business domain.

	// Wrap Service with middlewares. See handlers/middlewares.go
	service = handlers.WrapService(service)

	// Endpoint domain.
	var (
	{{range $i := .Service.Methods -}}
	    {{ if and (not $i.RequestStream) (not $i.ResponseStream) }}
    		{{ToLower $i.Name}}Endpoint = svc.Make{{$i.Name}}Endpoint(service)
        {{ end }}
	{{end}}
	)

	endpoints := svc.NewEndpoints()
	{{range $i := .Service.Methods -}}
	    {{ if and (not $i.RequestStream) (not $i.ResponseStream) }}
    		endpoints.{{$i.Name}}Endpoint = {{ToLower $i.Name}}Endpoint
        {{ end }}
	{{end}}

	// Wrap selected Endpoints with middlewares. See handlers/middlewares.go
	endpoints = handlers.WrapEndpoints(endpoints)

	return endpoints
}

// Run starts a new http server, gRPC server, and a debug server with the
// passed config and logger
func Run(cfg svc.Config) {
	service := handlers.NewService()
	endpoints := NewEndpoints(service)

	if cfg.GenericHTTPResponseEncoder == nil {
		cfg.GenericHTTPResponseEncoder = svc.EncodeHTTPGenericResponse
	}

	// WebSocket config
	wsCfg := svc.WebSocketConfig{
		Guard: func(ctx context.Context, r *http.Request) (context.Context, error) {
			return handlers.WebSocketGuard(ctx, service, r)
		},
		OriginChecker: func(r *http.Request) bool {
			return handlers.WebSocketOriginChecker(service, r)
		},
	}

	// Mechanical domain.
	errc := make(chan error)

	// Interrupt handler.
	go handlers.InterruptHandler(errc)

	// Debug listener.
	go func() {
		handlers.Logger.WithFields(logrus.Fields{
			"transport": "debug",
			"addr":      cfg.DebugAddr,
		}).Info("listening")

		m := http.NewServeMux()
		m.Handle("/debug/pprof/", http.HandlerFunc(pprof.Index))
		m.Handle("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
		m.Handle("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
		m.Handle("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
		m.Handle("/debug/pprof/trace", http.HandlerFunc(pprof.Trace))

		errc <- http.ListenAndServe(cfg.DebugAddr, m)
	}()

	// HTTP transport (includes WebSocket).
	go func() {
        handlers.Logger.WithFields(logrus.Fields{
			"transport": "HTTP",
			"addr":      cfg.HTTPAddr,
		}).Info("listening")
		h := svc.MakeHTTPHandler(handlers.Logger, endpoints, cfg.GenericHTTPResponseEncoder, wsCfg)
		errc <- http.ListenAndServe(cfg.HTTPAddr, h)
	}()

	// gRPC transport.
	go func() {
		handlers.Logger.WithFields(logrus.Fields{
            "transport": "gRPC",
            "addr":      cfg.GRPCAddr,
        }).Info("listening")
		ln, err := net.Listen("tcp", cfg.GRPCAddr)
		if err != nil {
			errc <- err
			return
		}

		srv := svc.MakeGRPCServer(endpoints)
		s := grpc.NewServer()
		pb.Register{{.Service.Name}}Server(s, srv)

		errc <- s.Serve(ln)
	}()

	// Run!
	handlers.Logger.WithError(<-errc).Info("exit")
}

